### ISSUE TITLE
双引号如何改成容易区分正反的形式？

### ISSUE THREAD

**Issue by hemuyao** [zhrln/typora-theme-han-ngaam#1]
您好，这个主题是我用过的写中文最漂亮的主题，感谢您的优化。

然而在大量书写中文的过程中发现，双引号采用的是有点类似西式标点的双引号，很难区分正反。本身typora“设置——编辑器——使用成对的符号”中对中文双引号的成对输入就是不支持的，如果无法区分正反的话，会导致写了一大篇文章，在导出的时候发现很多地方的引号用反了。

因此，您看有没有可能把中文双引号改成容易区分正反的形态呢？

非常感谢您的优化。

**Comment by zhrln** [comment]
hi，我目前使用的版本是 0.9.9.32.1，在编辑器里输入的引号确实能区分正反，请问是否有问题截图？
另一个可以检查一下「Markdown」选项卡里是否勾选了「智能引号」？

**Comment by hemuyao** [comment]
[我使用的版本是0.9.86，是目前的最新版。关于我发现的问题，我录屏展示了一下，请查看[问题描述](https://weibo.com/tv/v/J0GTvqkMX?fid=1034:4501648614293510)

**Comment by zhrln** [comment]
看标题栏像是 Windows 环境，这版本是在 Mac 上调的，晚上我回家换台机器试试看

**Comment by zhrln** [comment]
这是雅黑字体的设计问题，引号难以区分。Windows 下我改为宋体显示，看看效果如何

**Comment by hemuyao** [comment]
好的！非常感谢您的无私协助。新的主题已经完美解决了这个问题。:+1: :+1: :+1: :+1: :+1:
